"""empty message

Revision ID: 596f8dffc0c4
Revises: 4979ec506d4e
Create Date: 2023-01-07 12:16:37.916795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '596f8dffc0c4'
down_revision = '4979ec506d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('innodb_table_stats')
    op.drop_table('innodb_index_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('innodb_index_stats',
    sa.Column('database_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(collation='utf8mb3_bin', length=199), nullable=False),
    sa.Column('index_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('stat_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('stat_value', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sample_size', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('stat_description', mysql.VARCHAR(collation='utf8mb3_bin', length=1024), nullable=False),
    sa.PrimaryKeyConstraint('database_name', 'table_name', 'index_name', 'stat_name'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('innodb_table_stats',
    sa.Column('database_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(collation='utf8mb3_bin', length=199), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('n_rows', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('clustered_index_size', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sum_of_other_index_sizes', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('database_name', 'table_name'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    # ### end Alembic commands ###
